### ISSUE TITLE
Multiple plots

### ISSUE THREAD

**Issue by malenacandino** [wilkelab/sicegar#4]
I'm trying to use sicegar to fit double sigmoideal curves to NDVI data from multiple locations, the then obtain the inflection point of the curves. I have 16 datasets of at least 700 locations each, so I created a loop to fit the curves and extract the mid_point, but I also want to be able to asses how the curves fit my data visually, so I tried to include figureModelCurves(dataInput = fitObj_sm$normalizedInput,
                    sigmoidalFitVector = fitObj_sm$sigmoidalModel,
                    showParameterRelatedLines = TRUE, ylabelText = paste(ndvi[[i]], "NDVI")) 
in my loops. I end up with a vector that theoretically contains a list of ggplots, but I can't seem to be able to actually see them. Do you have any suggestions as to how to print multiple plots either in r or as a jpg in a folder? Thank you.

**Comment by clauswilke** [comment]
I would need a minimal reproducible example to be able to answer this question. The simpler the better.

**Comment by malenacandino** [comment]
I'm attaching a subset from my data with only 3 columns (3 different locations)

This is the loop I had written (apologies for the rough coding abilities) to get the midpoint values, which works fine, I just can't seem to be able to add code to have it print the graphs (ideally all of them together as a jpg):

library(sicegar)

ndvi<-read.csv("ndvi_example.csv")
column<-ncol(ndvi)-1
ToFill<-as.data.frame(matrix(NA, ncol=column, nrow=2))
dim(ToFill)
ndvi_loop<-ndvi[,-1]

for (i in 1:ncol(ndvi_loop)) {
  cols<-c(1,i)
  first<-ndvi[,cols]
  colnames(first)<-c("time", "intensity")
  first$time<-as.numeric(first$time)
  first$intensity<-as.numeric(first$intensity)
  normalizedInput <- normalizeData(dataInput = first,
                                   dataInputName = "doubleSigmoidalSample")
  sigmoidalModel <- multipleFitFunction(dataInput=normalizedInput,
                                        model="sigmoidal")
  fitObj_sm <- fitAndCategorize(dataInput = first)
  sigmoidalModelAugmented2 <- parameterCalculation(sigmoidalModel)
  doubleSigmoidalModel <- multipleFitFunction(dataInput=normalizedInput,
                                              model="doublesigmoidal")
  fitObj_dsm <- fitAndCategorize(dataInput = first)
  sigmoidalModelAugmented <- parameterCalculation(doubleSigmoidalModel)
  sig_midpoint<-sigmoidalModelAugmented2$midPoint_x
  doubsig_midpoint<-sigmoidalModelAugmented$midPoint1_x
  ToFill[1,i]<-sig_midpoint
  ToFill[2,i]<-doubsig_midpoint

}

Thanks!

Malena Candino
MS student

Department of Forest and Wildlife Ecology

University of Wisconsin-Madison

________________________________

**Comment by clauswilke** [comment]
Please read this: https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html
Also please use proper markdown formatting.

**Comment by clauswilke** [comment]
Actually, thinking some more about this, I think you should ask your question on stackoverflow.com. This reads like a user support question to me, and the issue tracker is for bugs and feature requests only. My comments regarding reprex and formatting apply to stackoverflow.com also.

I'm going to close this issue.
